### ISSUE TITLE
Sketch too big error when trying to compile for esp32 s2 mini

### ISSUE THREAD

**Issue by kvng1** [stooged/PS5-Server32#3]
Hi there, I tried compile the source for my esp32 s2 but got the errror Sketch too big, any idea? Thanks

![image](https://github.com/stooged/PS5-Server32/assets/41350055/50507b2b-f831-480c-980a-a90d6881a7a5)

**Comment by stooged** [comment]
you need to use a larger APP partition, the sketch is around 1.6mb so you need to use a 2mb app partition.

![part](https://github.com/stooged/PS5-Server32/assets/9004083/3d750c76-c4d6-4978-9c87-6d5097ec53d6)

**Comment by kvng1** [comment]
Sorry my bad, it's working good now. Thanks a lot.
