### ISSUE TITLE
etaHEN bin to .h

### ISSUE THREAD

**Issue by marek256** [stooged/PS5-Server32#5]
Hello, 
Sorry to contact you this way but I wanted to ask if the bin to .h converter works fine because if I drop new etahen.bin to that python script, I get a gz compressed filr, no etahen.bin I did not have problems.with goldhen.h on PS4
Thank you in advance

**Comment by stooged** [comment]
it works for me, if you drop the etahen.bin onto the script it will generate the [etahen.h](https://raw.githubusercontent.com/stooged/PS5-Server32/main/PS5_Server32/etahen.h) file.

if it is not producing the [etahen.h](https://raw.githubusercontent.com/stooged/PS5-Server32/main/PS5_Server32/etahen.h) file then it will be something to do with your python install.
