### ISSUE TITLE
10.1.1.1/admin.html - configuration page "not found" on ESP32-S3

### ISSUE THREAD

**Issue by russalex83** [stooged/PS5-Server32#6]
10.1.1.1/admin.html - configuration page "not found" on ESP32-S3

With 10.1.1.1/admin.html or ps5.local/admin.html the configuration page would not load, its says - "Not Found"

Everything else, works

**Comment by stooged** [comment]
if you are using the recently updated version there is no admin config page.
the project was changed to act like a usb flash drive, to make changes to the config you plug the esp into a pc and edit the config.ini 

the older version with the admin config page was archived here

https://github.com/stooged/PS5-Server32/tree/main/Archived_PS5_Server32
